
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Atiya
  host: localhost
development:
  <<: *default
  database: BlogApp_development

test:
  <<: *default
  database: BlogApp_test

production:
  <<: *default
  database: BlogApp_production
  username: BlogApp
  password: <%= ENV['BLOGAPP_DATABASE_PASSWORD'] %>
